### ISSUE TITLE
Sample Configuration

### ISSUE THREAD

**Issue by twosky2000** [martonborzak/beoplay-custom-component#1]
can you post a sample config?

**Comment by martonborzak** [comment]
Sorry about the late reply, notifications were turned off. Here is a config example:

```
media_player:
  - platform: beoplay
    host: 192.168.100.20
    name: Beoplay M5
  - platform: beoplay
    host: 192.168.100.22
    name: Beoplay S8
```
